apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: saadpatel2400/backend:42f6d97a4341288b8a428258fa8a15bbbc65b180
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000